//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DrugNorthQT.Properties {


  [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
  [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator","11.0.0.0")]
  internal sealed partial class Settings:global::System.Configuration.ApplicationSettingsBase {

	private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));

	public static Settings Default {
	  get {
		return defaultInstance;
	  }
	}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Configuration.DefaultSettingValueAttribute("")]
	public bool checkSaveLoginInfo {
	  get {
		return ((bool)(this["checkSaveLoginInfo"]));
	  }
	  set {
		this["checkSaveLoginInfo"] = value;
	  }
	}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Configuration.DefaultSettingValueAttribute("")]
	public string userName {
	  get {
		return ((string)(this["userName"]));
	  }
	  set {
		this["userName"] = value;
	  }
	}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Configuration.DefaultSettingValueAttribute("")]
	public string passUser {
	  get {
		return ((string)(this["passUser"]));
	  }
	  set {
		this["passUser"] = value;
	  }
	}

	[global::System.Configuration.UserScopedSettingAttribute()]
	[global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
	[global::System.Configuration.DefaultSettingValueAttribute("")]
	public int isServer {
	  get {
		return ((int)(this["isServer"]));
	  }
	  set {
		this["isServer"] = value;
	  }
	}
  }
}
